<?php

return [
    'India',
    'United Kingdom',
    'United States',
    'United Arab Emirates',
    'Australia',
    'South Africa',
    'New Zealand',
    'Singapore',
    'Canada',
    'Germany',
    'France',
    'Sri Lanka',
    'Pakistan',
    'Bangladesh',
    'Afghanistan',
    'Netherlands',
    'Ireland',
    'Zimbabwe',
    'West Indies',
    'Kuwait',
    'Oman',
    'Qatar',
    'Saudi Arabia',
    'Bahrain',
    'Malaysia',
    'Hong Kong',
    'Japan',
    'Switzerland',
    'Italy',
    'Spain',
    'Portugal',
    'Belgium',
    'Austria',
    'Norway',
    'Sweden',
    'Denmark',
    'Finland',
    'Greece',
    'Turkey',
    'Egypt',
    'Nigeria',
    'Kenya',
    'Brazil',
    'Argentina',
    'Mexico',
    // ... add more if needed, but this is already quite comprehensive for the target audience
];
